on:
  push:
    branches:
      - main

jobs:
  build-and-export:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2

    - name: Setup xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Create exportOptions.plist for Development Bypass
      run: |
        cat << EOF > exportOptions.plist
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>development</string>
            <key>compileBitcode</key>
            <false/>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>signingCertificate</key>
            <string>Apple Development</string>
            <key>provisioningProfiles</key>
            <dict>
                <!-- Specify your app's bundle identifier and a dummy profile -->
                <key>com.cvetest.app</key>
                <string>iOS Team Provisioning Profile: cve.test</string>
            </dict>
            <key>teamID</key>
            <string>3JFTY5BP58</string>
        </dict>
        </plist>
        EOF
      shell: bash

    - name: Build and Archive keyboardy scheme without Signing
      run: |
        xcodebuild -project cvetesting.xcodeproj -scheme keyboardy -sdk iphoneos -configuration Release archive -archivePath $(pwd)/keyboardy.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export keyboardy IPA without Signing
      run: |
        xcodebuild -exportArchive -archivePath $(pwd)/keyboardy.xcarchive -exportPath $(pwd)/keyboardyIPA -exportOptionsPlist $(pwd)/exportOptions.plist

    - name: Build and Archive usprebooter scheme without Signing
      run: |
        xcodebuild -project cvetesting.xcodeproj -scheme usprebooter -sdk iphoneos -configuration Release archive -archivePath $(pwd)/usprebooter.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export usprebooter IPA without Signing
      run: |
        xcodebuild -exportArchive -archivePath $(pwd)/usprebooter.xcarchive -exportPath $(pwd)/usprebooterIPA -exportOptionsPlist $(pwd)/exportOptions.plist

    - name: Upload keyboardy IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: keyboardy-ipa
        path: $(pwd)/keyboardyIPA/*.ipa

    - name: Upload usprebooter IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: usprebooter-ipa
        path: $(pwd)/usprebooterIPA/*.ipa
