name: Build, Archive, and Manual IPA Packaging

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    # Build and Archive keyboardy Scheme Without Signing
    - name: Archive keyboardy Scheme
      run: |
        xcodebuild -project cvetesting.xcodeproj \
                   -scheme keyboardy \
                   -sdk iphoneos \
                   -configuration Release \
                   archive \
                   -archivePath $(pwd)/keyboardy.xcarchive \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Package keyboardy Archive into IPA
      run: |
        mkdir -p keyboardyIPA/Payload
        cp -R keyboardy.xcarchive/Products/Applications/* keyboardyIPA/Payload/
        cd keyboardyIPA
        zip -r ../keyboardy.ipa Payload
        cd ..
      env:
        MD_APPLE_SDK_ROOT: /Applications/Xcode_15.2.app

    # Build and Archive usprebooter Scheme Without Signing
    - name: Archive usprebooter Scheme
      run: |
        xcodebuild -project cvetesting.xcodeproj \
                   -scheme usprebooter \
                   -sdk iphoneos \
                   -configuration Release \
                   archive \
                   -archivePath $(pwd)/usprebooter.xcarchive \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Package usprebooter Archive into IPA
      run: |
        mkdir -p usprebooterIPA/Payload
        cp -R usprebooter.xcarchive/Products/Applications/* usprebooterIPA/Payload/
        cd usprebooterIPA
        zip -r ../usprebooter.ipa Payload
        cd ..
      env:
        MD_APPLE_SDK_ROOT: /Applications/Xcode_15.2.app

    - name: Upload keyboardy IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: keyboardy-ipa
        path: keyboardy.ipa
            
    - name: Upload usprebooter IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: usprebooter-ipa
        path: usprebooter.ipa
