name: Build, Archive, and Export IPA for Both Schemes

on:
  push:
    branches:
      - main

jobs:
  build-and-export:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

      
    - name: Setup Xcode environment
      uses: sinoru/actions-setup-xcode@v2.0.2
      with:
          xcode-version: 15.2
          apple-id: ieatdogshit@icloud.com
          apple-id-password: jhxz-gohu-bfbc-xcqq
          
    - name: Build and Archive keyboardy scheme
      run: |
        xcodebuild -project cvetesting.xcodeproj -scheme keyboardy -sdk iphoneos -configuration Release archive -archivePath $(pwd)/keyboardy.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export keyboardy IPA
      run: |
        xcodebuild -exportArchive -archivePath $(pwd)/keyboardy.xcarchive -exportPath $(pwd)/keyboardyIPA -exportOptionsPlist exportOptions.plist

    - name: Build and Archive usprebooter scheme
      run: |
        xcodebuild -project cvetesting.xcodeproj -scheme usprebooter -sdk iphoneos -configuration Release archive -archivePath $(pwd)/usprebooter.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export usprebooter IPA
      run: |
        xcodebuild -exportArchive -archivePath $(pwd)/usprebooter.xcarchive -exportPath $(pwd)/usprebooterIPA -exportOptionsPlist exportOptions.plist

    - name: Upload keyboardy IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: keyboardy-ipa
        path: $(pwd)/keyboardyIPA/*.ipa

    - name: Upload usprebooter IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: usprebooter-ipa
        path: $(pwd)/usprebooterIPA/*.ipa
