name: Build and Archive Without Signing

on:
  push:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Build and Archive keyboardy Scheme
      run: |
        xcodebuild -project cvetesting.xcodeproj \
                   -scheme keyboardy \
                   -sdk iphoneos \
                   -configuration Release \
                   archive \
                   -archivePath $(pwd)/keyboardy.xcarchive \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Build and Archive usprebooter Scheme
      run: |
        xcodebuild -project cvetesting.xcodeproj \
                   -scheme usprebooter \
                   -sdk iphoneos \
                   -configuration Release \
                   archive \
                   -archivePath $(pwd)/usprebooter.xcarchive \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Package keyboardy Archive into IPA (Dummy)
      run: |
        mkdir -p $(pwd)/keyboardyIPA/Payload
        cp -R $(pwd)/keyboardy.xcarchive/Products/Applications/* $(pwd)/keyboardyIPA/Payload/
        cd $(pwd)/keyboardyIPA
        zip -r keyboardy.ipa Payload
        cd $(pwd)

    - name: Package usprebooter Archive into IPA (Dummy)
      run: |
        mkdir -p $(pwd)/usprebooterIPA/Payload
        cp -R $(pwd)/usprebooter.xcarchive/Products/Applications/* $(pwd)/usprebooterIPA/Payload/
        cd $(pwd)/usprebooterIPA
        zip -r usprebooter.ipa Payload
        cd $(pwd)

    - name: Upload keyboardy IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: keyboardy-ipa
        path: $(pwd)/keyboardyIPA/keyboardy.ipa

    - name: Upload usprebooter IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: usprebooter-ipa
        path: $(pwd)/usprebooterIPA/usprebooter.ipa
