name: Build, Archive, and Manual IPA Packaging

on:
  push:
    branches:
      - main

jobs:
  build-and-package:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    # Archive keyboardy Scheme Without Signing
    - name: Archive keyboardy Scheme
      run: |
        xcodebuild -project cvetesting.xcodeproj \
                   -scheme keyboardy \
                   -sdk iphoneos \
                   -configuration Release \
                   archive \
                   -archivePath ${GITHUB_WORKSPACE}/keyboardy.xcarchive \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    # Package keyboardy Archive into IPA
    - name: Package keyboardy Archive into IPA
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/keyboardyIPA/Payload
        cp -R ${GITHUB_WORKSPACE}/keyboardy.xcarchive/Products/Applications/* ${GITHUB_WORKSPACE}/keyboardyIPA/Payload/
        cd ${GITHUB_WORKSPACE}/keyboardyIPA
        zip -r ${GITHUB_WORKSPACE}/keyboardy.ipa Payload
        cd ${GITHUB_WORKSPACE}

    # Archive usprebooter Scheme Without Signing
    - name: Archive usprebooter Scheme
      run: |
        xcodebuild -project cvetesting.xcodeproj \
                   -scheme usprebooter \
                   -sdk iphoneos \
                   -configuration Release \
                   archive \
                   -archivePath ${GITHUB_WORKSPACE}/usprebooter.xcarchive \
                   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    # Package usprebooter Archive into IPA
    - name: Package usprebooter Archive into IPA
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/usprebooterIPA/Payload
        cp -R ${GITHUB_WORKSPACE}/usprebooter.xcarchive/Products/Applications/* ${GITHUB_WORKSPACE}/usprebooterIPA/Payload/
        cd ${GITHUB_WORKSPACE}/usprebooterIPA
        zip -r ${GITHUB_WORKSPACE}/usprebooter.ipa Payload
        cd ${GITHUB_WORKSPACE}

    # Upload keyboardy IPA to Artifacts
    - name: Upload keyboardy IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: keyboardy-ipa
        path: ${GITHUB_WORKSPACE}/keyboardy.ipa

    # Upload usprebooter IPA to Artifacts
    - name: Upload usprebooter IPA to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: usprebooter-ipa
        path: ${GITHUB_WORKSPACE}/usprebooter.ipa
